
# Setup
title:               Subhojit
tagline:             Computer Science, Programming, Philosophy and Life
url:                 http://venustus.in
email:				 subhojit.ds@gmail.com
description: 		 space is reserved for blogs
paginate:            1
baseurl:             ""
url: 				"blog.subhojit.in"
twitter_username: 	subhojitds
github_username:  	subhojitgit